### ISSUE TITLE
Spec licensing

### ISSUE THREAD

**Issue by ahelwer** [nano-o/Distributed-termination-detection#2]
Here as well

**Comment by nano-o** [comment]
Waiting for Stephan's input on this one (he's a contributor).
There's also this spec which I think is interesting: https://github.com/nano-o/streamlet/

**Comment by muenchnerkindl** [comment]
Hi Giuliano,

indeed, Streamlet looks interesting. Perhaps beef it up with a few comments (and a link to the blog post in the TLA module), in particular about the properties verified, and open a pull request?

Cheers,
Stephan

**Comment by ahelwer** [comment]
MIT license was added
